### ISSUE TITLE
configs_file_extension not working as intended

### ISSUE THREAD

**Issue by dpeachey** [adamkirchberger/nectl#9]
Hi,

Setting 'configs_file_extension' does not appear to work. When I set:

`configs_file_extension = "json"`

... the config is still generated with the "txt" extension.

Thanks,

Dan

P.S. great project btw!

**Comment by adamkirchberger** [comment]
Hi Dan,

I've managed to replicate the issue and applied a fix in PR #10 

Thanks for raising this, let me know if you notice any other issues.

Adam
